# Generated by Django 5.0.4 on 2024-04-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_featuredarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredarticle',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
