# Generated by Django 5.0.4 on 2024-05-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_featuredarticle_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredarticle',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
    ]
