# Generated by Django 5.0.4 on 2024-05-01 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_featuredarticle_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('uid', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='featuredarticle',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RssCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=1000)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.rssfeed')),
            ],
        ),
    ]
