# Generated by Django 5.0.4 on 2024-05-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_featuredarticle_summary_alter_rsscache_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsscache',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_cache', to='blog.rssfeed'),
        ),
    ]
