# Generated by Django 5.0.4 on 2024-05-01 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeed',
            name='uid',
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rss_feeds', to='blog.user'),
            preserve_default=False,
        ),
    ]
